version: '3'

volumes:
  main_local_postgres_data: {}
  main_local_postgres_data_backups: {}
  main_local_prometheus_data: {}
  main_local_grafana_data: {}

services:
  django: &django
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: main_local_django
    container_name: main_local_django
    depends_on:
      - postgres
      - redis
    volumes:
      - .:/app:z
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.postgres
    ports:
      - '8000:8000'
    command: /start

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: main_production_postgres
    container_name: main_local_postgres
    volumes:
      - main_local_postgres_data:/var/lib/postgresql/data
      - main_local_postgres_data_backups:/backups
    env_file:
      - ./.envs/.local/.postgres

  # docs:
  #   image: main_local_docs
  #   container_name: main_local_docs
  #   build:
  #     context: .
  #     dockerfile: ./compose/local/docs/Dockerfile
  #   env_file:
  #     - ./.envs/.local/.django
  #   volumes:
  #     - ./docs:/docs:z
  #     - ./config:/app/config:z
  #     - ./main:/app/main:z
  #   ports:
  #     - '9000:9000'
  #   command: /start-docs

  redis:
    image: redis:6
    container_name: main_local_redis

  # celeryworker:
  #   <<: *django
  #   image: main_local_celeryworker
  #   container_name: main_local_celeryworker
  #   depends_on:
  #     - redis
  #     - postgres
  #   ports: []
  #   command: sh -c "celery -A config.celery_app worker -l info -Q high_priority,default,low_priority -c 1"

  default_worker: &default_worker
    <<: *django
    image: main_local_celeryworker
    container_name: default_worker
    depends_on:
      - redis
      - postgres
    ports: []
    command: sh -c "celery -A config.celery_app worker -l info --queues=default_queue --concurrency=2 --hostname=default_queue_worker@%h --without-mingle"

  mail_worker:
    <<: *default_worker
    container_name: mail_worker
    command: sh -c "celery -A config.celery_app worker -l info --queues=mail_queue --concurrency=1 --hostname=mail_queue_worker@%h --without-mingle"

  photo_worker:
    <<: *default_worker
    container_name: photo_worker
    command: sh -c "celery -A config.celery_app worker -l info --queues=photo_queue --concurrency=4 --hostname=photo_queue_worker@%h --without-mingle"

  celerybeat:
    <<: *django
    image: main_local_celerybeat
    container_name: main_local_celerybeat
    depends_on:
      - redis
      - postgres
    ports: []
    command: /start-celerybeat

  flower:
    <<: *django
    image: main_local_flower
    container_name: main_local_flower
    ports:
      - '5555:5555'
    command: /start-flower

  prometheus:
    image: prom/prometheus
    container_name: main_local_prometheus
    volumes:
      - main_local_prometheus_data:/prometheus
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - 9090:9090
  
  grafana:
    image: grafana/grafana
    container_name: main_local_grafana
    environment:
      GF_INSTALL_PLUGINS: "grafana-clock-panel,grafana-simple-json-datasource"
    volumes:
      - main_local_grafana_data:/var/lib/grafana
    ports:
      - 3000:3000
    depends_on:
      - prometheus