global:
  scrape_interval:     15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ['localhost:9090']

  - job_name: flower
    static_configs:
      - targets: ['flower:5555']

  - job_name: django
    scrape_interval: 10s
    metrics_path: '/prometheus/metrics'
    static_configs:
    - targets: ['django:8000']